(function (libIntro, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(libIntro.YIR_intro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Intro Movie
	this.instance = new libIntro.IntroMovie();
	this.instance.setTransform(1123.6,465,1,1,0,0,0,101.2,-23.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(155));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-605.7,194.8,3458.8,870.8);


// symbols:
(libIntro.YearInReview = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADBPTQgWgFgUgIQgVgJgSgMQgSgMgPgQQgPgPgMgSQgMgTgIgUQgIgVgFgWQgEgXAAgYQAAgXAEgXQAFgWAIgVQAIgUAMgTQAMgSAPgQQAPgQASgMQASgNAVgIQAVgJAXgEQAXgFAZAAQAeAAAaAFQAYAFAVAJQAcAMAsAmIgyA5QgdgagbgOQgPgHgRgEQgRgEgTAAQgfAAgbANQgaALgUAWQgUAVgLAdQgKAdAAAgQAAAgAKAdQALAdAUAWQAUAWAaAMQAbAMAfAAQAVAAARgEQAQgEAQgIQAagMAggdIAyAyQgTATgSANQgTAPgVAKQgWALgZAFQgaAFgeAAQgYAAgXgEgAMePQIiXjHIhFBGIAACBIhNAAIAAm7IBNAAIAADfIDTjfIBfAAIi4C/IDAD8gAhePQIgthrIjRAAIguBrIhPAAIDCm+IBIAAIDDG+gAinMgIhNixIhMCxICZAAgAt8PQIAAm7IDGAAQAiAAAbAIQAaAIAUAPQATAPAKAVQAKAVAAAaQAAATgGARQgEAOgJANQgQAVgcAPQAUAHAPAJQARAJALANQAMANAGARQAGASAAAWQAAAdgLAXQgLAXgWAQQgWAPgeAIQgeAIglAAgAsvOLICAAAQAVAAAPgEQAQgEALgHQALgIAGgMQAGgLAAgPQAAgPgGgLQgFgLgMgIQgLgHgRgEQgSgEgWAAIh7AAgAsvLQIBqAAQASAAAQgEQAPgEALgHQALgIAGgLQAGgMAAgPQAAgNgFgLQgFgKgKgIQgKgHgOgEQgPgEgSAAIhwAAgACVDeQgXgFgWgJQgVgIgSgNQgSgMgQgQQgPgPgMgTQgKgSgIgUQgIgVgFgWQgEgWAAgWQAAgXAEgWQAFgXAIgUQAIgVALgSQAMgTAPgPQAQgQASgNQASgMAVgJQAWgJAXgEQAYgFAZAAQAZAAAYAFQAXAEAVAJQAVAIASANQATAMAPAQQAPAQANASQALASAJAVQAIAUAEAWQAFAXAAAXQAAAVgFAXQgEAWgJAUQgIAVgMATQgMASgQAQQgPAPgSANQgTAMgVAJQgVAJgXAFQgYAEgZAAQgZAAgYgEgACJiRQgbALgUAWQgUAWgKAcQgLAdAAAgQAAAeALAdQALAdAUAVQAUAXAbAMQAdAMAgAAQAgAAAcgMQAbgMAUgWQAUgVALgdQALgcAAgfQAAgggLgdQgLgdgUgVQgVgWgbgMQgcgNggAAQghAAgcANgAmCDeQgXgFgWgJQgVgIgSgNQgSgMgQgQQgPgPgMgTQgMgSgIgUQgIgVgFgWQgEgWAAgWQAAgXAEgWQAFgXAIgUQAIgVANgSQAMgTAPgPQAQgQASgNQASgMAVgJQAWgJAXgEQAYgFAZAAQAZAAAYAFQAXAEAVAJQAVAIASANQATAMAPAQQAPAQANASQALASAJAVQAIAUAEAWQAFAXAAAXQAAAVgFAXQgEAWgJAUQgIAVgMATQgMASgQAQQgPAPgSANQgTAMgVAJQgVAJgXAFQgYAEgZAAQgZAAgYgEgAmOiRQgbALgUAWQgUAWgKAcQgLAdAAAgQAAAeALAdQALAdAUAVQAUAXAbAMQAdAMAgAAQAgAAAcgMQAbgMAUgWQAUgVALgdQALgcAAgfQAAgggLgdQgLgdgUgVQgVgWgbgMQgcgNggAAQghAAgcANgAM1DbIiXjHIhFBGIAACBIhNAAIAAm5IBNAAIAADeIDTjeIBfAAIi4C/IDAD6gAuSDbIAAm5IBNAAIAAFyIDpAAIAABHgAB8oZIgthqIjPAAIgtBqIhQAAIDDm9IBGAAIDCG9gAAzrIIhKixIhMCxICWAAg");
	this.shape.setTransform(605.4,67.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(513.9,-30.5,183.2,196.8);


(libIntro.WrapBall = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CA3538").s().p("EhnTADZIG0mxMDHzAAAIm0Gxg");
	this.shape.setTransform(2797.5,242.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CA3538").s().p("EhnSADZIGzmxMDHyAAAImzGxg");
	this.shape_1.setTransform(661.2,168.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],-396.4,-28.8,-63.4,-4.4).s().p("EhEtgAJQgUhVgNhPQAGgOAKgFQAOgJAvgKIAAABQDggjJPgFQHagFSdANMBiqAABIAAGzMhkfgACQv0gOm3ADQpkAEi/AhIgBgBQgnALgJAEQgPAIACANQgxiAggiGg");
	this.shape_2.setTransform(1868.5,244.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],-179.6,-14.1,153.2,10.2).s().p("A6oAIIhchzIgCgLQAIgJAGgCQAGgDAVgGIABABQCegdHQgEQGOgDOtAOQLTALFPgHQHngKAxgwQhYCKhrB3QghAngqArQhJAfjUAKQksAPrlgMQsYgMlLABQnDADhzAbIgBgBQgRAHgIAHQACAJADADQh4h2hNhYg");
	this.shape_3.setTransform(1644.2,331.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],-105,-10.9,68.3,4.2).s().p("AuVANIh+g6QgIgFgDgGQABgEAFgDIAAAAQA0gSDkgEQDngEIPAJQHSAHDagDQFDgFA7gbQiKBLiNA9Ih1AtQg3APilADQikAElWgHQo0gJgXAUQgDADANAHQiig0hwgsg");
	this.shape_4.setTransform(1645.8,391.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],57.3,0,-57.1,0).s().p("AF8BzIiMgFIAEAAQhCgQiLgSQiFgShGgSQh/gniig8Ih3g5QA3AXDKAmQCOAaEFAoQEhAuBsAXQBLAQAMALQgGAEgEABIgZADQgmACgrAAIhMgCg");
	this.shape_5.setTransform(1599.4,398.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],143.6,0.1,-143.5,0.1).s().p("AQRF/IAGgFQglggjugvQjygwqFhoQoChSjpgxQjrgug0gkQhbhYhph1IhZhyQAtArGKBOQEeA4IkBYQNuCMFDA/QFDA/BJAsIgGAPQiBBGiWBEIhzAsIAFgEg");
	this.shape_6.setTransform(1608.4,360.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],199.4,0,-199.3,0).s().p("AUXHFQmVhTxyi4QtjiMldhIQldhKhKg7QgxiAggiHQgUhVgNhPQAtBBIGBpQFrBJNRCLQJJBgENAuQL0B+EoBFQEbBCAXAxQhZCKhrB5QgpAvghAhQgRg0mUhSg");
	this.shape_7.setTransform(1624.8,285.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],396.6,29,63.6,4.6).s().p("AdcDzMhiqgABIAAmzMBkfAACQP0AOG3gDQJkgEC/ghIABABQAngLAKgEQAOgIgCgNQAxCAAgCGQAUBVANBPQgGAOgKAGQgOAIgvAKIAAgBQjgAjpPAFIksACQnmAAtlgKg");
	this.shape_8.setTransform(1391.5,166.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],179.8,14.3,-153,-10).s().p("A5DgrQAhgmAqgsQBJgfDUgKQEsgPLlAMQMYAMFLgBQHDgDBzgbIABABQARgHAIgHQgCgJgDgDQB4B2BNBYIBcBzIACALQgIAJgFACQgHADgVAGIgBgBQieAdnQAEQmOADutgOQrTgLlPAHQnnAKgyAwQBaiKBqh3g");
	this.shape_9.setTransform(1615.8,78.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#CA3538","#CC3B3E","#D24D4F","#DD6B6D","#EB9596","#FECBCC","#F3ACAD","#E48183","#D96062","#D0484A","#CB3A3D","#CA3538"],[0.149,0.192,0.251,0.322,0.4,0.482,0.525,0.592,0.659,0.722,0.776,0.824],105.2,11.1,-68.1,-4).s().p("AsIgbIB1gtQA3gPClgDQCkgDFWAFQI0AKAXgUQADgDgNgHQCiA0BwAsIB+A6QAIAFAEAGQgCAEgFADIAAgBQg0ATjkAEQjoAEoOgJQnSgHjaADQlDAFg7AbQCKhLCNg9g");
	this.shape_10.setTransform(1614.2,19.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],-57.1,0,57.3,0).s().p("AE8A4QiOgakFgoQkhguhsgXQhLgQgMgLQAGgEAEgBIAZgDQBFgDBYADICMAFIgEAAQBCAQCLASQCFASBGASQB/AnCiA8IB3A5Qg3gXjKgmg");
	this.shape_11.setTransform(1660.6,11.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],-143.5,0,143.6,0).s().p("APkEKQkeg4okhZQtuiLlDg/QlDg/hJgsIAGgPQCBhGCWhEIB1gtIgNAKQAkAgDvAvQDyAwKFBoQICBSDpAxQDrAuAzAjQBcBZBpB1IBZByQgtgrmKhOgAwJmCIAAAAIAAAAg");
	this.shape_12.setTransform(1651.6,50.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#000000","#070707","#1A1A1A","#333333","#2C2C2C","#141414","#050505","#000000"],[0,0.125,0.302,0.478,0.518,0.698,0.863,1],-199.3,0,199.4,0).s().p("AWXGhQlrhJtRiLQpJhgkNguQr0h+kohFQkbhCgXgxQBZiKBrh5QApgvAhghQARA0GUBSQGVBTRyC4QNjCMFdBIQFdBKBKA7QAxCAAgCHQAUBVANBPQgthBoGhpg");
	this.shape_13.setTransform(1635.2,124.9);

	this.addChild(this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,3458.8,410.6);


(libIntro.whiterec2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egg9AFKIAAqTMBB7AAAIAAKTg");
	this.shape.setTransform(211.1,33);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,422.1,66);


(libIntro.whitebox = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EihHAqMMAAAhUXMFCPAAAMAAABUXg");
	this.shape.setTransform(1031.3,270.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,2062.5,540.2);


(libIntro.RedCircle = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CA3538").s().p("A5vZwQqqqrAAvFQAAvDKqqsQKsqqPDAAQPFAAKqKqQKrKsAAPDQAAPFqrKrQqqKqvFAAQvDAAqsqqg");
	this.shape.setTransform(233.1,233.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,466.1,466.1);


(libIntro.RedArrowLine = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CA3538").s().p("Egk6ADeIAAm7MBJ1AAAIAAG7g");
	this.shape.setTransform(236.3,22.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,472.7,44.6);


(libIntro.Logo = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#808184").s().p("AheBeQgngnAAg3QAAg2AognQAngoA2AAQA3AAAnAoQAoAnAAA2QAAA2goAoQgmAng4AAQg3AAgngngAhRhRQghAiAAAvQAAAwAhAhQAiAjAvgBQAwABAigjQAhghAAgwQAAgvghgiQgjghgvgBQguABgjAhgAAkBIIgBgDIAAgRQAAgZgOgIQgJgFgTAAIgUAAIAAA6IgaAAIAAiRIA0AAQAZAAANAGQAXAJAAAcQAAAUgOAJQgIADgOACQARACAJAMQAIALAAAMIAAAVIABAIIABACgAgbgCIAXAAQAPAAAJgDQAPgGAAgRQAAgQgKgFQgJgFgVgBIgWAAg");
	this.shape.setTransform(1955.2,278.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CA3538").s().p("AnIQ6QjThZiiijQijijhZjSQhcjbAAjuQAAjuBcjaQBZjTCjiiQCiijDThZQDahcDuAAQDuAADbBcQDSBZCjCjQCjCiBZDTQBcDaAADuQAADuhcDbQhZDTijCiQiiCjjTBZQjbBcjuAAQjuAAjahcg");
	this.shape_1.setTransform(608.7,179.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AQGRyIAAyRQAAhDgGhVQgFhTghhMQgfhJhEg0QhDgzh/AAQiLAAhJA1QhIA1gjBMQgiBNgGBKQgGBMAAAvIAASwIqPAAIAAysQAAgsgGhNQgGhNgdhMQgehLhEg4QhCg3h8AAQiLAAhLA5QhLA5gkBQQgjBNgHBWQgFBXAAArIAASRIqSAAMAAAgiWIJmAAIAADpIAIAAQATgiApg1QAlgyBIgzQBEgxBsglQBrgkCaAAQBGAABXAQQBUAQBUAsQBSAqBPBNQBPBMBDB6QBniiCqhzQCsh0D8AAQA5AABKAJQBIAHBMAYQBMAYBPAsQBPAtBBBGQBNBUAuBIQAwBKAaBfQAZBeAIB+QAIByAADBIAASwg");
	this.shape_2.setTransform(1763.6,175.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AoJQlQjdhqiUipQiSiohJjQQhKjRAAjJQAAjIBKjQQBJjQCSipQCSioDfhrQDehrErAAQEsAADfBrQDfBsCRCnQCTCpBJDQQBJDOAADKQAADLhJDPQhKDQiSCoQiTCpjdBqQjeBrktAAQksAAjdhrgAjIoAQhgAqhJBJQhIBIgrBoQgpBoAAB1QAAB2ApBoQArBpBIBHQBKBKBfApQBfAqBpAAQBrAABfgqQBfgpBJhKQBLhKAohmQAqhmAAh4QAAh2gqhnQgohlhLhLQhIhJhggqQhegqhsAAQhqAAheAqg");
	this.shape_3.setTransform(1474,179.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AnFQ6QjXhbidihQicighcjWQhbjXAAjzQAAjyBZjWQBYjWCeifQCbieDVhcQDVhbD1AAQDYAADCBFQDCBFCaB5QCXB4BqCrQBqCqArDKIqaAAQgeg6gmg1Qgog3g2gsQg5gshMgbQhPgchlAAQh2gDhfApQheAqhGBLQhGBMglBpQgmBpAAB2QAAB3AmBnQAlBoBGBLQBFBMBfApQBeAqB3AAQBpAABLgcQBNgbA4gqQA2gpAog0QAmgwAeg3IKeAAQgtC9hmCjQhmCliWB8QiUB7jBBHQjBBHjdAAQj4AAjYhbg");
	this.shape_4.setTransform(1235.2,179.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AlGWnIAA6iIk2AAIAAn0IE2AAIAAn1IKQjCIAAK3IEzAAIAAH0IkzAAIAAaig");
	this.shape_5.setTransform(978.9,144.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("Ak0RnQhLgHhfgfQhdgehag2QhZg3hJhdQhDhSgmhKQgnhLgUhMQgWhKgGhcQgGhZAAhzIAA0iIKRAAIAAS/QAAA3AGBPQAGBNAgBDQAgBEBJAvQBJAwCEgBQBGABBDgWQBDgVA2gyQA2gyAfhXQAghZAAiCIAAy3IKRAAMAAAAiWIpuAAIAAjqIgIAAQgzBrhIA8QhJA8hOAfQhQAfhKAIQhLAIhCAAQg2AAhNgIg");
	this.shape_6.setTransform(808.9,183.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AlBVvQimhfg/h3IgIAAIAADpIp2AAMAAAgtOIKRAAIAANlQBWheBigzQBggxBbgYQBXgYBJgEQBLgEAfAAQCqAADBBCQDABBCfCLQCfCMBoDbQBqDdAAE2QAAEphgDhQhfDhiaCTQibCWjJBJQjIBJjSAAQjpABimhfgAjwjMQhkAwhIBPQhIBPgkBiQgkBkAABoQAAB0AmBmQAmBnBFBOQBFBNBlAvQBiAtB8AAQB/AABjgvQBogyBFhMQBHhMAphpQAohnAAhsQgBhrglhmQgmhihHhPQhHhMhkgxQhkgwh5ABQiCgBhnAwg");
	this.shape_7.setTransform(416.3,148.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AKNWoIiPmpIv4AAIiaGpIslAAMASZgtOIJNAAMASNAtOgAksGuIJkAAIktvpIgLAAg");
	this.shape_8.setTransform(146.7,144.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CA3538").s().p("AlGFHQiIiHAAjAQAAi+CIiJQCIiIC+AAQDAAACICIQCICJAAC+QAADAiICHQiICIjAAAQi+AAiIiIg");
	this.shape_9.setTransform(1073.6,251);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1968.7,297.4);


(libIntro.intro_invisible = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AneKJIAA0RIO9AAIAAURg");
	this.shape.setTransform(48,65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(libIntro.FastFact = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Egz5AQcQgWgEgUgIQgUgJgSgLQgSgMgPgPQgPgOgLgSQgMgRgIgUQgIgTgEgVQgEgVAAgXIAAgBQAAgWAEgVQAEgVAIgUQAIgUAMgRQAMgRAPgPQAPgPARgMQATgMAUgIQAUgIAXgFQAWgEAYAAQAYAAAXAEQAWAFAVAIQAUAIASAMQARALAPAPQAPAPAMARQALASAIATQAIAUAFAUQAEAWAAAWIAAABQAAAWgEAWQgFAVgIAUQgIATgMARQgLASgPAPQgPAOgSAMQgSAMgUAIQgVAJgWAEQgXAFgYAAQgYAAgXgFgEgz9ALOQgXAKgRASQgQASgKAXQgJAYAAAbIAAABQAAAbAJAYQAKAYARASQARATAXAKQAYAKAbAAQAcAAAXgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAgBQAAgagJgZQgJgYgRgSQgSgSgXgKQgYgLgbAAQgbAAgYALgEgsDAQgQgSAAgNgKQgNgJgIgSIiIlFQgFgOAAgJQAAgTANgNQAOgNATAAQARAAANAJQALAIAGAPIBpEQIBqkTQAFgMALgIQANgJAPAAQATAAAOANQANAMAAATQAAAKgFAKIiJFJQgIASgMAJQgOAKgSAAgAPMQTQg0gVgYgRQgRgMAAgXQAAgSAMgMQANgNASAAQAPAAAMAJQAYASAaAJQAbALAeAAQAcAAAQgLQAQgKAAgTIAAgBQAAgSgQgLQgRgLgzgOQgkgJgWgIQgbgLgRgNQgSgOgJgVQgKgWAAgeIAAgBQAAgcAKgYQALgXAUgRQAUgRAbgJQAbgJAgAAQAlAAAiAKQAhAJAdASQAIAFAGAJQAGALAAAMQAAASgMAMQgNANgSAAQgMAAgLgHQgYgOgVgHQgWgHgVAAQgaAAgPALQgOAKAAAPIAAACQAAAUASALQARAKA4AOQAiAJAXAKQAZALARAOQARAPAIATQAJAVAAAbIAAABQAAAfgLAZQgLAXgVARQgUARgdAJQgcAIgiAAQg3gEgbgIgAmhQTQg1gVgXgRQgSgMAAgXQAAgSANgMQANgNARAAQAPAAAMAJQAZASAZAJQAcALAdAAQAdAAAQgLQAQgKAAgTIAAgBQAAgSgQgLQgRgLg0gOQgjgJgWgIQgbgLgRgNQgTgOgJgVQgKgWAAgeIAAgBQAAgcALgYQALgXATgRQAUgRAbgJQAbgJAgAAQAmAAAiAKQAgAJAdASQAJAFAFAJQAHALAAAMQAAASgNAMQgMANgSAAQgNAAgLgHQgYgOgVgHQgWgHgVAAQgaAAgOALQgOAKAAAPIAAACQAAAUASALQARAKA4AOQAhAJAXAKQAaALAQAOQARAPAJATQAJAVAAAbIAAABQAAAfgLAZQgMAXgUARQgVARgcAJQgcAIgiAAQg4gEgagIgEA1GAQWQgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgNAOgUAAQgTAAgNgOQgOgNAAgTIAAlMQAAgTAOgNQANgOATAAICSAAQAbAAAsALQAfALAUAVQASARAJAZQAKAYAAAeIAAABQAAAYgGAVQgGAUgLAQQgLAPgQAMQgPAMgUAIIBBBOQAPATAAAQQAAATgOAMQgNAMgRAAQgPAAgMgHgEAyPANBIBeAAQARAAANgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgFgLQgFgMgKgHQgJgIgNgEQgOgDgRAAIhcAAgEAukAQUQgLgIgHgPIgchCIi5AAIgdBFQgGAOgLAHQgLAIgPAAQgRAAgNgNQgMgMAAgSQAAgIAFgMICTlLQAHgRAOgKQAOgJATAAIAFAAQATAAANAJQAOAKAHARICTFLQAFAKAAAJQAAASgNANQgNANgSAAQgQAAgLgJgEArgANpIB0AAIg6iKgAe0QPQgNgNAAgTIAAh4IiIi4QgMgQAAgRQAAgSAOgNQANgNAUAAQAOAAAMAIQAKAGAJAOIBmCTIBoiUQAJgOAKgGQAMgIANAAQAVAAAMANQAMANAAATQAAAQgMAQIiHC3IAAB6QAAATgOANQgNAOgTAAQgUAAgNgOgAVvQPQgOgNAAgTIAAklIhYAAQgSAAgMgMQgNgNAAgRQAAgSANgMQAMgNASAAIEOAAQARAAANANQAMAMAAASQAAARgMANQgNAMgRAAIhZAAIAAElQAAATgOANQgNAOgTAAQgUAAgNgOgAL8QUQgLgIgGgPIgchCIi5AAIgdBFQgGAOgMAHQgLAIgOAAQgSAAgMgNQgNgMAAgSQAAgIAGgMICSlLQAIgRAOgKQAOgJASAAIAGAAQASAAAOAJQANAKAIARICSFLQAFAKAAAJQAAASgMANQgNANgTAAQgPAAgMgJgAI4NpIB1AAIg7iKgABbQPQgOgNAAgTIAAlMQAAgTAOgNQANgOATAAIB+AAQAlAAAeALQAeAKAVAUQAVATALAbQALAbAAAfIAAACQAAARgEARQgDAQgHAOQgMAbgYATQgXASgfAKQgfAJgjAAIhHAAIAABUQAAATgNANQgNAOgUAAQgTAAgNgOgACpNJIBKAAQARAAAOgFQANgEAKgJQAJgJAFgLQAFgMAAgOIAAgBQAAgPgFgMQgFgMgKgIQgKgIgOgEQgOgEgRAAIhIAAgAqdQPQgNgNAAgTIAAlPQAAgTANgOQAOgNATAAQATAAAOANQANAOAAATIAAFPQAAATgNANQgOAOgTAAQgTAAgOgOgAtiQPQgOgNAAgTIAAh+IiqAAIAAB+QAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlPQAAgTANgOQAOgNATAAQATAAAOANQANAOAAATIAAB8ICqAAIAAh8QAAgTAOgOQANgNAUAAQATAAAOANQANAOAAATIAAFPQAAATgNANQgOAOgTAAQgUAAgNgOgA2MQPQgOgNAAgTIAAklIhYAAQgSAAgMgMQgNgNAAgRQAAgSANgMQAMgNASAAIEOAAQARAAANANQAMAMAAASQAAARgMANQgNAMgRAAIhZAAIAAElQAAATgOANQgNAOgTAAQgUAAgNgOgA9OQWQgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlMQAAgTANgNQAOgOATAAICSAAQAaAAAsALQAfALAVAVQASARAJAZQAJAYAAAeIAAABQAAAYgGAVQgGAUgLAQQgLAPgPAMQgPAMgUAIIBABOQAPATAAAQQAAATgNAMQgNAMgSAAQgOAAgMgHgEggFANBIBeAAQAQAAAOgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgGgLQgEgMgKgHQgJgIgOgEQgNgDgRAAIhcAAgEAkEAQZQgTAAgOgNQgNgOAAgTIAAlIQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEgnFAQZQgTAAgOgNQgNgOAAgTIAAlIQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEA/wADUQgWgEgVgIQgUgJgSgLQgRgMgPgPQgPgOgMgSQgLgRgIgUQgJgTgEgVQgEgVAAgXIAAAAQAAgVAEgVQAFgVAIgUQAIgUAMgRQAMgRAOgPQAPgPASgMQASgMAUgIQAVgIAWgFQAXgEAYAAQAYAAAXAEQAWAFAUAIQAUAIASAMQASALAPAPQAPAPALARQAMASAIATQAIAUAEAUQAEAWAAAWIAAAAQAAAVgEAWQgEAVgIAUQgJATgLARQgMASgPAPQgPAOgSAMQgSAMgUAIQgUAJgXAEQgWAFgYAAQgYAAgXgFgEA/sgB4QgXAKgRASQgRASgJAXQgJAYAAAbIAAAAQAAAaAJAYQAJAYARASQASATAWAKQAYAKAcAAQAbAAAYgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAAAQAAgZgKgZQgJgYgRgSQgRgSgXgKQgYgLgbAAQgcAAgXALgACSDUQgWgEgUgIQgUgJgSgLQgSgMgPgPQgPgOgLgSQgKgRgIgUQgIgTgEgVQgEgVAAgXIAAAAQAAgVAEgVQAEgVAIgUQAIgUAKgRQAMgRAPgPQAPgPARgMQATgMAUgIQAUgIAXgFQAWgEAYAAQAYAAAXAEQAWAFAVAIQAUAIASAMQARALAPAPQAPAPAMARQALASAIATQAIAUAFAUQAEAWAAAWIAAAAQAAAVgEAWQgFAVgIAUQgIATgMARQgLASgPAPQgPAOgSAMQgSAMgUAIQgVAJgWAEQgXAFgYAAQgYAAgXgFgACOh4QgXAKgRASQgQASgKAXQgJAYAAAbIAAAAQAAAaAJAYQAKAYARASQARATAXAKQAYAKAbAAQAcAAAXgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAAAQAAgZgJgZQgJgYgRgSQgSgSgXgKQgYgLgbAAQgbAAgYALgAuLDUQgVgEgUgIQgTgIgRgMQgSgMgOgOQgOgPgMgRQgLgSgIgTQgIgUgEgVQgEgVAAgXIAAAAQAAgVAEgVQAEgWAIgTQAHgUAMgRQALgRAPgPQAOgPASgMQARgMAUgIQAUgIAWgFQAXgEAYAAQAfAAAxAMQAgAKAcAVQAIAFAEAKQAGAKAAALQAAATgNANQgOANgTAAQgNAAgOgJQgUgPgUgHQgWgIgYAAQgaAAgXALQgWAKgQASQgRASgJAXQgJAYAAAbIAAAAQAAAaAJAYQAJAYAQASQAQATAWAKQAYAKAaAAQAcAAAWgIQAUgIAVgRQAMgKAQAAQARAAANANQANAMAAASQAAATgQAOQgnAdgYAKQgTAGgVAEQgVAEgZAAQgXAAgWgFgEgigADUQgVgEgUgIQgTgIgRgMQgSgMgOgOQgOgPgMgRQgLgSgIgTQgIgUgEgVQgEgVAAgXIAAAAQAAgVAEgVQAEgWAIgTQAHgUAMgRQALgRAPgPQAOgPASgMQARgMAUgIQAUgIAWgFQAXgEAYAAQAfAAAxAMQAgAKAcAVQAIAFAEAKQAGAKAAALQAAATgNANQgOANgTAAQgNAAgOgJQgUgPgUgHQgWgIgYAAQgaAAgXALQgWAKgQASQgRASgJAXQgJAYAAAbIAAAAQAAAaAJAYQAJAYAQASQAQATAWAKQAYAKAaAAQAcAAAWgIQAUgIAVgRQAMgKAQAAQARAAANANQANAMAAASQAAATgQAOQgnAdgYAKQgTAGgVAEQgVAEgZAAQgXAAgWgFgEhlGADOQgdgKgbgTQgJgGgFgJQgFgJAAgLQAAgTANgNQANgNASAAQAOAAALAJQAUANATAHQATAGAWAAQAPAAAMgDQAMgEAJgIQAKgHAFgLQAFgLAAgOIAAgBQAAgNgGgLQgFgLgKgHQgKgHgOgEQgNgEgRAAQgUAAgUAFQgUAGgDAAQgQAAgagTQgKgGgEgIQgEgJABgMIAIiOQABgRAMgLQAMgMAQAAIC3AAQAQAAAMAMQAMAMAAARQAAARgMAMQgMALgQAAIiOAAIgFBJQAdgHAaAAQAgAAAaAHQAbAIAUAQQAUARALAXQALAbAAAiIAAABQAAAhgLAbQgLAbgVATQgVATgdAKQgdALgiAAQg2gFgWgGgEBG0ADMQgRgGgOgJQgPgIgLgMQgMgMgJgOQgJgPgGgRQgHgSgDgUIgDjvQAAgTANgOQAOgNATAAQAUAAANANQANAOAAATIAADBQAAAZAHAUQAGATAMANQALAOARAGQARAHAVAAQAVAAARgHQARgGAMgNQALgNAGgSQAHgTAAgZIAAjEQAAgTANgOQANgNAUAAQATAAAOANQANAOAAATIAADAIgDAtQgEAUgGATQgGARgKAPQgJAPgMAMQgMAMgOAIQgPAJgRAGQgwAMgcAAQg2gEgWgIgAJWDMQgRgGgOgJQgOgIgMgMQgMgMgJgOQgJgPgGgRQgGgSgDgUIgDjvQAAgTANgOQANgNAUAAQATAAAOANQANAOAAATIAADBQAAAZAGAUQAGATAMANQAMAOARAGQAQAHAWAAQAVAAARgHQAQgGAMgNQAMgNAGgSQAGgTAAgZIAAjEQAAgTAOgOQANgNATAAQAUAAANANQAOAOAAATIAADAIgEAtQgDAUgGATQgHARgJAPQgJAPgMAMQgMAMgPAIQgOAJgRAGQgxAMgcAAQg1gEgXgIgEguOADYQgRAAgMgKQgMgKgHgSIhSjvIhTDvQgHASgMAKQgMAKgRAAIgJAAQgRAAgMgKQgNgKgGgSIh2lIIgDgRQAAgUAOgMQAOgNATAAQAQAAAMAJQAMAJAFAPIBUD/IBTj9QAGgRAMgJQAMgLARAAIAIAAQARAAAMAKQAMAKAFARIBUD9IBUj/QAEgPAMgJQAMgJAQAAQATAAANANQAOAMAAATIgEASIh2FIQgGASgMAKQgNAKgQAAgEA4gADNQgagKgVgQQgSgNAAgXQAAgSANgNQANgNASAAQAOAAAOAJQAOALAMAFQAOAGAPAAQAOAAALgFQAKgEAIgIQAHgJAEgNQAEgNAAgSIAAjiQAAgTANgOQAOgNATAAQAUAAANANQANAOAAATIAADmQAAAlgKAcQgKAcgTATQgTATgdAKQgbAKgiAAQgiAAgegKgEBivADHQgNgNAAgTIAAh4IiIi2QgLgQAAgRQAAgSANgNQAOgNATAAQAPAAAMAIQAKAGAJAOIBmCTIBoiUQAJgOAKgGQALgIAOAAQAVAAAMANQAMANAAATQAAAQgMAQIiIC1IAAB6QAAATgNANQgNAOgUAAQgTAAgOgOgEBTWADIQgOgOAAgTIAAlMQAAgTAOgOQANgNATAAIAKAAQAQAAAMAHQAKAHAKANICyDoIAAjXQAAgTANgNQAOgNATAAQATAAANANQANANAAATIAAFMQAAAUgNANQgOAOgTAAIgDAAQgPAAgMgIQgKgGgLgNIi5jxIAADfQAAATgNAOQgNANgTAAQgTAAgNgNgEBQpADOQgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgNAOgUAAQgTAAgNgOQgOgNAAgTIAAlKQAAgTAOgNQANgOATAAICSAAQAbAAAsALQAfALAUAVQASARAJAZQAKAYAAAeIAAABQAAAYgGAVQgGAUgLAOQgLAPgQAMQgPAMgUAIIBBBOQAPATAAAQQAAATgOAMQgNAMgRAAQgPAAgMgHgEBNygAFIBeAAQARAAANgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgFgLQgFgMgKgHQgJgIgNgEQgOgDgRAAIhcAAgEAytADOQgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgNAOgUAAQgTAAgNgOQgOgNAAgTIAAlKQAAgTAOgNQANgOATAAICSAAQAbAAAsALQAfALAUAVQASARAJAZQAKAYAAAeIAAABQAAAYgGAVQgGAUgLAOQgLAPgQAMQgPAMgUAIIBBBOQAPATAAAQQAAATgOAMQgNAMgRAAQgPAAgMgHgEAv2gAFIBeAAQARAAANgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgFgLQgFgMgKgHQgJgIgNgEQgOgDgRAAIhcAAgEAriADHQgNgNAAgTIAAlNQAAgTANgOQAOgNATAAQATAAAOANQANAOAAATIAAFNQAAATgNANQgOAOgTAAQgTAAgOgOgEAiLADHQgOgNAAgTIAAh+IiqAAIAAB+QAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlNQAAgTANgOQAOgNATAAQATAAAOANQANAOAAATIAAB8ICqAAIAAh8QAAgTAOgOQANgNAUAAQATAAAOANQANAOAAATIAAFNQAAATgNANQgOAOgTAAQgUAAgNgOgAZhDHQgOgNAAgTIAAkjIhYAAQgSAAgMgMQgNgNAAgRQAAgSANgMQAMgNASAAIEOAAQARAAANANQAMAMAAASQAAARgMANQgNAMgRAAIhZAAIAAEjQAAATgOANQgNAOgTAAQgUAAgNgOgAQoDHQgOgNAAgTIAAkjIhYAAQgSAAgMgMQgNgNAAgRQAAgSANgMQAMgNASAAIEOAAQARAAANANQAMAMAAASQAAARgMANQgNAMgRAAIhZAAIAAEjQAAATgOANQgNAOgTAAQgUAAgNgOgAlODPQgIgFgJgLIh4ieIg1AyIAABUQAAATgNANQgNAOgUAAQgTAAgNgOQgOgNAAgTIAAlNQAAgTAOgOQANgNATAAQAUAAANANQANAOAAATIAACNICripQAJgJAJgFQAJgEAMAAQATAAAMANQAMAMAAARQAAATgRAQIh2BuICBCgQAMAQAAARQAAATgNANQgOANgUAAQgMAAgKgGgA5pDHQgNgNAAgTIAAh+IirAAIAAB+QAAATgNANQgNAOgUAAQgTAAgNgOQgOgNAAgTIAAlNQAAgTAOgOQANgNATAAQAUAAANANQANAOAAATIAAB8ICrAAIAAh8QAAgTANgOQAOgNATAAQAUAAANANQANAOAAATIAAFNQAAATgNANQgNAOgUAAQgTAAgOgOgEgqcADGQgPgPAAgVIAAgBQAAgWAPgPQAPgOAWAAQAXAAAPAOQAOAPAAAWIAAABQAAAVgOAPQgPAPgXAAQgWAAgPgPgEhCGADIQgNgOAAgTIAAlMQAAgTANgOQAOgNATAAIAJAAQAQAAAMAHQAKAHAKANICzDoIAAjXQAAgTANgNQANgNATAAQATAAANANQAOANAAATIAAFMQAAAUgOANQgNAOgTAAIgDAAQgQAAgMgIQgKgGgKgNIi5jxIAADfQAAATgNAOQgOANgTAAQgTAAgNgNgEhN4ADOQgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlKQAAgTANgNQAOgOATAAICSAAQAaAAAsALQAfALAVAVQASARAJAZQAJAYAAAeIAAABQAAAYgGAVQgGAUgLAOQgLAPgPAMQgPAMgUAIIBABOQAPATAAAQQAAATgNAMQgNAMgSAAQgOAAgMgHgEhQvgAFIBeAAQAQAAAOgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgGgLQgEgMgKgHQgJgIgOgEQgNgDgRAAIhcAAgEhUbADMQgLgIgGgPIgchCIi5AAIgdBFQgGAOgMAHQgLAIgOAAQgSAAgMgNQgNgMAAgSQAAgIAGgMICSlJQAIgRAOgKQAOgJASAAIAGAAQASAAAOAJQANAKAIARICSFJQAFAKAAAJQAAASgMANQgNANgTAAQgPAAgMgJgEhXfAAhIB1AAIg7iIgEhfCADIQgNgOAAgTIAAkgIghAIIgQADQgQAAgMgMQgMgMAAgQQAAgOAIgLQAIgKAOgFIA8gRQAcgIAPAAIABAAQATAAANAOQAOANAAATIAAFQQAAATgOAOQgNANgTAAQgTAAgNgNgEBbQADRQgTAAgNgNQgOgOAAgTIAAlGQAAgTAOgNQANgOATAAIDpAAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAIi7AAIAABWICgAAQARAAAMAMQAMAMAAARQAAAPgMAMQgMAMgRAAIigAAIAABYIC+AAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAgEAltADRQgTAAgOgNQgNgOAAgTIAAlGQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAAPgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgA2HDRQgTAAgNgNQgOgOAAgTIAAlGQAAgTAOgNQANgOATAAIDpAAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAIi7AAIAABWICgAAQARAAAMAMQAMAMAAARQAAAPgMAMQgMAMgRAAIigAAIAABYIC+AAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAgEg6LADRQgTAAgOgNQgNgOAAgTIAAlGQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAAPgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEhKrADRQgTAAgOgNQgNgOAAgTIAAlGQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAAPgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEgqcgAZQgPgPAAgWIAAgBQAAgWAPgOQAPgPAWAAQAXAAAPAPQAOAOAAAWIAAABQAAAWgOAPQgPAOgXAAQgWAAgPgOgEBTmgIaQgFgFAAgJQAAgQASgEQAXgFAMgPQAMgPgBgWQgRgEgMgNQgNgOAAgSIAAgBQAAgWANgNQAOgOAXAAQAMAAAKAEQAKAFAHAJQAHAJAEAMQADAMAAAQIAAACQAAAggJAZQgJAZgRARQgOANgSAIQgSAIgRAAQgMAAgGgHgEA17gJyQgWgEgVgIQgUgJgSgLQgRgMgPgPQgPgOgMgSQgLgRgIgUQgJgTgEgVQgEgVAAgXIAAgBQAAgWAEgVQAFgVAIgUQAIgUAMgRQAMgRAOgPQAPgPASgMQASgMAUgIQAVgIAWgFQAXgEAYAAQAYAAAXAEQAWAFAUAIQAUAIASAMQASALAPAPQAPAPALARQAMASAIATQAIAUAEAUQAEAWAAAWIAAABQAAAWgEAWQgEAVgIAUQgJATgLARQgMASgPAPQgPAOgSAMQgSAMgUAIQgUAJgXAEQgWAFgYAAQgYAAgXgFgEA13gPAQgXAKgRASQgRASgJAXQgJAYAAAbIAAABQAAAbAJAYQAJAYARASQASATAWAKQAYAKAcAAQAbAAAYgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAgBQAAgagKgZQgJgYgRgSQgRgSgXgKQgYgLgbAAQgcAAgXALgA2YpyQgVgEgUgIQgTgIgRgMQgSgMgOgOQgOgPgMgRQgLgSgIgTQgIgUgEgVQgEgVAAgXIAAgBQAAgWAEgVQAEgWAIgTQAHgUAMgRQALgRAPgPQAOgPASgMQARgMAUgIQAUgIAWgFQAXgEAYAAQAfAAAxAMQAgAKAcAVQAIAFAEAKQAGAKAAALQAAATgNANQgOANgTAAQgNAAgOgJQgUgPgUgHQgWgIgYAAQgaAAgXALQgWAKgQASQgRASgJAXQgJAYAAAbIAAABQAAAbAJAYQAJAYAQASQAQATAWAKQAYAKAaAAQAcAAAWgIQAUgIAVgRQAMgKAQAAQARAAANANQANAMAAASQAAATgQAOQgnAdgYAKQgTAGgVAEQgVAEgZAAQgXAAgWgFgEggagJyQgTgEgRgIQgRgIgPgMQgPgLgMgPQgMgOgKgSQgJgRgHgTQgGgUgEgVIgDgtIAAgBQAAgWADgWQAEgVAHgUQAGgUAKgRQAKgRAMgPQAMgPAPgLQAPgMARgIQARgIATgFQAUgEAUAAQAVAAATAEQATAFARAIQARAIAPALQAPAMAMAPQAMAOAKARQAJARAHAUQAGAUAEAVQADAVAAAXIAAABQAAAXgDAVQgEAWgGATQgHAUgJARQgKASgMAPQgNAOgOAMQgPAMgRAIQgSAIgTAEQgTAFgVAAQgUAAgUgFgEggXgPDQgRAKgMASQgMASgHAYQgGAZAAAcIAAABQAAAdAHAZQAGAYAMASQANASAQAKQASAKAUAAQAVAAARgKQARgKAMgSQAMgSAGgYQAHgYAAgdIAAgBQAAgcgHgZQgHgYgMgSQgMgSgRgKQgRgKgVAAQgUAAgRAJgEhCLgJyQgWgEgUgIQgUgJgSgLQgSgMgPgPQgPgOgLgSQgMgRgIgUQgIgTgEgVQgEgVAAgXIAAgBQAAgWAEgVQAEgVAIgUQAIgUAMgRQAMgRAPgPQAPgPARgMQATgMAUgIQAUgIAXgFQAWgEAYAAQAYAAAXAEQAWAFAVAIQAUAIASAMQARALAPAPQAPAPAMARQALASAIATQAIAUAFAUQAEAWAAAWIAAABQAAAWgEAWQgFAVgIAUQgIATgMARQgLASgPAPQgPAOgSAMQgSAMgUAIQgVAJgWAEQgXAFgYAAQgYAAgXgFgEhCPgPAQgXAKgRASQgQASgKAXQgJAYAAAbIAAABQAAAbAJAYQAKAYARASQARATAXAKQAYAKAbAAQAcAAAXgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAgBQAAgagJgZQgJgYgRgSQgSgSgXgKQgYgLgbAAQgbAAgYALgEhTGgJyQgWgEgVgIQgUgJgSgLQgRgMgPgPQgPgOgMgSQgLgRgIgUQgJgTgEgVQgEgVAAgXIAAgBQAAgWAEgVQAFgVAIgUQAIgUAMgRQAMgRAOgPQAPgPASgMQASgMAUgIQAVgIAWgFQAXgEAYAAQAYAAAXAEQAWAFAUAIQAUAIASAMQASALAPAPQAPAPALARQAMASAIATQAIAUAEAUQAEAWAAAWIAAABQAAAWgEAWQgEAVgIAUQgJATgLARQgMASgPAPQgPAOgSAMQgSAMgUAIQgUAJgXAEQgWAFgYAAQgYAAgXgFgEhTKgPAQgXAKgRASQgRASgJAXQgJAYAAAbIAAABQAAAbAJAYQAJAYARASQASATAWAKQAYAKAcAAQAbAAAYgKQAXgKARgSQARgSAJgYQAJgYAAgbIAAgBQAAgagKgZQgJgYgRgSQgRgSgXgKQgYgLgbAAQgcAAgXALgAwSp6QgRgGgOgJQgOgIgMgMQgMgMgJgOQgJgPgGgRQgGgSgDgUIgDjxQAAgTANgOQANgNAUAAQATAAAOANQANAOAAATIAADDQAAAZAGAUQAGATAMANQAMAOARAGQAQAHAWAAQAVAAARgHQAQgGAMgNQAMgNAGgSQAGgTAAgZIAAjGQAAgTAOgOQANgNATAAQAUAAANANQAOAOAAATIAADCIgEAtQgDAUgGATQgHARgJAPQgJAPgMAMQgMAMgPAIQgOAJgRAGQgxAMgcAAQg1gEgXgIgEg7HgJ6QgRgGgOgJQgOgIgMgMQgMgMgJgOQgJgPgGgRQgGgSgDgUIgDjxQAAgTANgOQANgNAUAAQATAAAOANQANAOAAATIAADDQAAAZAGAUQAGATAMANQAMAOARAGQAQAHAWAAQAVAAARgHQAQgGAMgNQAMgNAGgSQAGgTAAgZIAAjGQAAgTAOgOQANgNATAAQAUAAANANQAOAOAAATIAADCIgEAtQgDAUgGATQgHARgJAPQgJAPgMAMQgMAMgPAIQgOAJgRAGQgxAMgcAAQg1gEgXgIgEBPLgJ7Qg0gVgYgRQgRgMAAgXQAAgSAMgMQANgNASAAQAPAAAMAJQAYASAaAJQAbALAeAAQAcAAAQgLQAQgKAAgTIAAgBQAAgSgQgLQgRgLgzgOQgkgJgWgIQgbgLgRgNQgSgOgJgVQgKgWAAgeIAAgBQAAgcAKgYQALgXAUgRQAUgRAbgJQAbgJAgAAQAlAAAiAKQAhAJAdASQAIAFAGAJQAGALAAAMQAAASgMAMQgNANgSAAQgMAAgLgHQgYgOgVgHQgWgHgVAAQgaAAgPALQgOAKAAAPIAAACQAAAUASALQARAKA4AOQAiAJAXAKQAZALARAOQARAPAIATQAJAVAAAbIAAABQAAAfgLAZQgLAXgVARQgUARgdAJQgcAIgiAAQg3gEgbgIgEA9CgJ/QgNgNAAgTIAAh4IiIi4QgMgQAAgRQAAgSAOgNQANgNAUAAQAOAAAMAIQAKAGAJAOIBmCTIBoiUQAJgOAKgGQAMgIANAAQAVAAAMANQAMANAAATQAAAQgMAQIiHC3IAAB6QAAATgOANQgNAOgTAAQgUAAgNgOgEAoAgJ/QgOgNAAgTIAAlMQAAgTAOgNQANgOATAAIB+AAQAlAAAeALQAeAKAVAUQAVATALAbQALAbAAAfIAAACQAAARgEARQgDAQgHAOQgMAbgYATQgXASgfAKQgfAJgjAAIhHAAIAABUQAAATgNANQgNAOgUAAQgTAAgNgOgEApOgNFIBKAAQARAAAOgFQANgEAKgJQAJgJAFgLQAFgMAAgOIAAgBQAAgPgFgMQgFgMgKgIQgKgIgOgEQgOgEgRAAIhIAAgEAk/gJ/QgOgNAAgTIAAjSIhRB9QgHAMgJAFQgKAHgMAAQgMAAgKgHQgJgFgHgMIhQh7IAADRQAAATgOANQgNANgTAAQgTAAgNgNQgNgNAAgTIAAlPQAAgTAOgOQANgNATAAIALAAQAOAAALAHQAKAGAHALIBvC2IBwi3QAIgLAKgGQAKgGAOAAIAKAAQATAAAOANQANAOAAATIAAFOQAAATgNANQgOAOgTAAQgTAAgNgOgASNp/QgNgNAAgTIAAklIhZAAQgRAAgNgMQgNgNAAgRQAAgSANgMQANgNARAAIEOAAQASAAAMANQANAMAAASQAAARgNANQgMAMgSAAIhZAAIAAElQAAATgNANQgNAOgUAAQgTAAgOgOgAJSp+QgOgOAAgTIAAlOQAAgTAOgOQANgNATAAIAKAAQAQAAAMAHQAKAHAKANICyDqIAAjZQAAgTANgNQAOgNATAAQATAAANANQANANAAATIAAFOQAAAUgNANQgOAOgTAAIgDAAQgPAAgMgIQgKgGgLgNIi5jzIAADhQAAATgNAOQgNANgTAAQgTAAgNgNgAAUp4QgKgGgJgLIhYhyIhKAAIAABcQAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlMQAAgTANgNQAOgOATAAICSAAQAaAAAqALQAfALAVAVQASARAJAZQAJAYAAAeIAAABQAAAYgGAVQgGAUgLAQQgLAPgPAMQgPAMgUAIIBABOQAPATAAAQQAAATgNAMQgNAMgSAAQgOAAgMgHgAihtNIBeAAQAQAAAOgEQANgEAJgIQAJgIAFgLQADgLAAgNIAAgBQAAgPgEgLQgEgMgKgHQgJgIgOgEQgNgDgRAAIhcAAgAmcp4QgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlMQAAgTANgNQAOgOATAAICSAAQAaAAAsALQAfALAVAVQASARAJAZQAJAYAAAeIAAABQAAAYgGAVQgGAUgLAQQgLAPgPAMQgPAMgUAIIBABOQAPATAAAQQAAATgNAMQgNAMgSAAQgOAAgMgHgApTtNIBeAAQAQAAAOgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgGgLQgEgMgKgHQgJgIgOgEQgNgDgRAAIhcAAgEgncgJ8QgOgLAAgUQAAgOAJgOICbkSIigAAQgRAAgMgLQgMgMAAgQQAAgRAMgMQAMgMARAAIDkAAQATAAALALQAMALAAAUQAAAUgNAZIipEyQgJAQgLAHQgLAIgNAAQgUAAgOgLgEgq5gJ+QgNgOAAgTIAAkiIggAIIgQADQgRAAgMgMQgMgMAAgQQAAgOAJgLQAIgKAOgFIA7gRQAcgIAPAAIACAAQATAAANAOQANANAAATIAAFSQAAATgNAOQgNANgTAAQgTAAgOgNgEgxRgJ4QgKgGgJgLIhahyIhKAAIAABcQAAATgNANQgOAOgTAAQgTAAgOgOQgNgNAAgTIAAlMQAAgTANgNQAOgOATAAICSAAQAaAAAsALQAfALAVAVQASARAJAZQAJAYAAAeIAAABQAAAYgGAVQgGAUgLAQQgLAPgPAMQgPAMgUAIIBABOQAPATAAAQQAAATgNAMQgNAMgSAAQgOAAgMgHgEg0IgNNIBeAAQAQAAAOgEQANgEAJgIQAJgIAFgLQAFgLAAgNIAAgBQAAgPgGgLQgEgMgKgHQgJgIgOgEQgNgDgRAAIhcAAgEhNYgJ/QgNgNAAgTIAAlMQAAgTANgNQAOgOATAAIDrAAQARAAANAMQAMANAAARQAAASgMAMQgNAMgRAAIi9AAIAABaICiAAQASAAAMAMQAMAMAAASQAAARgMAMQgMANgSAAIiiAAIAAB4QAAATgNANQgOAOgTAAQgTAAgOgOgEBIkgJ1QgTAAgOgNQgNgOAAgTIAAlIQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEBCSgJ1QgTAAgOgNQgNgOAAgTIAAlIQAAgTANgNQAOgOATAAIDpAAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAIi8AAIAABWIChAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIihAAIAABYIC/AAQARAAAMAMQAMAMAAASQAAARgMAMQgMALgRAAgEAuxgJ1QgTAAgOgNQgNgOAAgTIAAlLQAAgTANgOQAOgNATAAQATAAAOANQANAOAAATIAAElICrAAQASAAAMAMQAMANAAARQAAASgMAMQgMAMgSAAgAaFp1QgTAAgNgNQgOgOAAgTIAAlIQAAgTAOgNQANgOATAAIDpAAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAIi7AAIAABWICgAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIigAAIAABYIC+AAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAgADgp1QgTAAgNgNQgOgOAAgTIAAlIQAAgTAOgNQANgOATAAIDpAAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAIi7AAIAABWICgAAQARAAAMAMQAMAMAAARQAAARgMAMQgMAMgRAAIigAAIAABYIC+AAQARAAAMAMQANAMAAASQAAARgNAMQgMALgRAAg");
	this.shape.setTransform(710.5,197);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CA3538").s().p("APKDUQgVgEgTgIQgUgIgRgMQgRgMgPgOQgOgPgMgRQgLgSgIgTQgIgUgEgVQgEgVAAgXIAAAAQAAgVAEgVQAEgWAIgTQAHgUAMgRQAMgRAOgPQAPgPARgMQARgMAUgIQAVgIAWgFQAWgEAYAAQAgAAAxAMQAgAKAbAVQAIAFAFAKQAFAKAAALQAAATgNANQgNANgUAAQgNAAgOgJQgUgPgUgHQgWgIgYAAQgaAAgXALQgVAKgRASQgQASgKAXQgJAYAAAbIAAAAQAAAaAJAYQAJAYARASQAPATAWAKQAYAKAaAAQAcAAAWgIQAUgIAWgRQAMgKAPAAQASAAAMANQANAMAAASQAAATgPAOQgoAdgYAKQgSAGgWAEQgVAEgZAAQgWAAgXgFgAtXDLQg0gVgYgRQgRgMAAgXQAAgSAMgMQANgNASAAQAPAAAMAJQAYASAZAJQAcALAeAAQAcAAAQgLQAQgKAAgTIAAgBQAAgSgQgLQgRgLgzgOQgkgJgWgIQgbgLgRgLQgTgOgIgVQgLgWAAgeIAAgBQAAgcALgYQALgXATgRQAUgRAbgJQAbgJAhAAQAlAAAiAKQAgAJAeASQAIAFAFAJQAHALAAAMQAAASgNAMQgMANgSAAQgMAAgMgHQgXgOgWgHQgWgHgUAAQgaAAgPALQgOAKAAAPIAAACQAAAUASALQARAKA4AOQAiAJAWAKQAaALARAMQAQAPAJATQAJAVAAAbIAAABQAAAfgLAZQgLAXgVARQgUARgdAJQgcAIgiAAQg3gEgbgIgAZtDGQgPgPAAgVIAAgBQAAgWAPgPQAPgOAWAAQAXAAAPAOQAOAPAAAWIAAABQAAAVgOAPQgPAPgXAAQgWAAgPgPgAVcDHQgNgNAAgTIAAkjIhYAAQgSAAgNgMQgNgNABgRQgBgSANgMQANgNASAAIEOAAQARAAAMANQANAMAAASQAAARgNANQgMAMgRAAIhZAAIAAEjQAAATgOANQgNAOgTAAQgUAAgOgOgAKyDMQgLgIgHgPIgchCIi4AAIgeBFQgFAOgMAHQgLAIgOAAQgSAAgNgNQgMgMAAgSQAAgIAFgMICTlJQAIgRANgKQAPgJASAAIAFAAQATAAAOAJQANAKAHARICTFJQAFAKAAAJQAAASgMANQgNANgTAAQgQAAgLgJgAHuAhIB0AAIg6iIgAAhDHQgNgNAAgTIAAlKQAAgTANgNQANgOAUAAIDrAAQARAAAMAMQANANAAARQAAASgNAMQgMAMgRAAIi9AAIAABaICiAAQARAAAMAMQANAMAAAQQAAARgNAMQgMANgRAAIiiAAIAAB4QgBATgNANQgNAOgTAAQgUAAgNgOgAm0DHQgOgNAAgTIAAkjIhZAAQgRAAgNgMQgMgNAAgRQAAgSAMgMQANgNARAAIEOAAQASAAANANQAMAMAAASQAAARgMANQgNAMgSAAIhYAAIAAEjQAAATgOANQgNAOgUAAQgTAAgNgOgAwnDMQgLgIgHgPIgchCIi4AAIgeBFQgFAOgMAHQgLAIgOAAQgSAAgNgNQgMgMAAgSQAAgIAFgMICTlJQAIgRANgKQAPgJASAAIAFAAQATAAAOAJQANAKAHARICTFJQAFAKAAAJQAAASgMANQgOANgSAAQgQAAgLgJgAzrAhIB0AAIg6iIgA64DHQgNgNAAgTIAAlKQAAgTANgNQANgOAUAAIDrAAQARAAAMAMQANANAAARQAAASgNAMQgMAMgRAAIi9AAIAABaICiAAQARAAAMAMQANAMAAAQQAAARgNAMQgMANgRAAIiiAAIAAB4QgBATgNANQgNAOgTAAQgUAAgNgOgAZtgZQgPgPAAgWIAAgBQAAgWAPgOQAPgPAWAAQAXAAAPAPQAOAOAAAWIAAABQAAAWgOAPQgPAOgXAAQgWAAgPgOg");
	this.shape_1.setTransform(710.1,29);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(55.9,7.3,1309.3,295.5);


(libIntro.arrow_bottom = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CE242F").s().p("AjGAAIGNnlIAAPLg");
	this.shape.setTransform(34,48.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape,p:{x:34}}]}).to({state:[{t:this.shape,p:{x:32.7}}]},1).to({state:[{t:this.shape,p:{x:31.4}}]},1).to({state:[{t:this.shape,p:{x:30.2}}]},1).to({state:[{t:this.shape,p:{x:28.9}}]},1).to({state:[{t:this.shape,p:{x:27.6}}]},1).to({state:[{t:this.shape,p:{x:26.3}}]},1).to({state:[{t:this.shape,p:{x:25.1}}]},1).to({state:[{t:this.shape,p:{x:23.8}}]},1).to({state:[{t:this.shape,p:{x:22.5}}]},1).to({state:[{t:this.shape,p:{x:21.2}}]},1).to({state:[{t:this.shape,p:{x:20}}]},1).to({state:[{t:this.shape,p:{x:21.2}}]},1).to({state:[{t:this.shape,p:{x:22.5}}]},1).to({state:[{t:this.shape,p:{x:23.8}}]},1).to({state:[{t:this.shape,p:{x:25.1}}]},1).to({state:[{t:this.shape,p:{x:26.3}}]},1).to({state:[{t:this.shape,p:{x:27.6}}]},1).to({state:[{t:this.shape,p:{x:28.9}}]},1).to({state:[{t:this.shape,p:{x:30.2}}]},1).to({state:[{t:this.shape,p:{x:31.4}}]},1).to({state:[{t:this.shape,p:{x:32.7}}]},1).to({state:[{t:this.shape,p:{x:34}}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.3,0,52.7,97.3);


(libIntro._3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgGTAg2QjEghiwhAIlCiWIkUjHQibiGAAjFQAAiyCEiEQCEiECyAAQCfAACGBvQC8CeC+BNQDNBPDvAAQEHAACkiKQCniMAAjoIAAgMQAAiAg3hlQg4hjhphDQhthEiYgjQiWgjjCAAIiPAAQiiAAh1h1Qh1h2AAiiQAAiyDEjIIMwszI0HAAQikgBh2h1Qhyh1AAihQAAilByh0QB2h2CkABIf7AAQDNAACBBuQCGBwAAC7QAACchMB+Qg3BeiQCMIs3MSQDnAmC5BMQDTBUCVCFQCnCQBYDHQBhDcAAEWIAAAOQAAEohqD9QhmD8jFC1QjHC7kWBkQkcBqlaAAQjdgBjHgig");
	this.shape.setTransform(186.9,275.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(34,61.9,305.9,427.4);


(libIntro._2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRCAhSQjcAAiJhzQiNh4AAjNQAAiEA+h1QA9h1B1heISsvSQGVlNCVjGQBYh2AphyQAmhwAAiDQAAkFieiSQiViKj/AAQjAAAihBXQiVBTi2DBQh4CHi+AAQiwAAh7h7Qh4h7AAiwQAAihBph+IELkFQCSh1CehPQCqhPDCgpQDHgqDoAAQFGABENBaQEIBbC+CtQDCCqBmDuQBnDzAAEhIAAAMQAAEFhEDTQhDDKiKC5QiBCujZDBInmGOIqpISIW0AAQCnAAB2B2QB1B1AACnQAACkh1B1Qh2BzinAAg");
	this.shape.setTransform(186.7,269);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(27.8,56,317.9,426);


(libIntro._1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AB5ffQiBiHAAi7MAAAgtYIlGBVIihAXQikAAh4h1Qh4h1AAihQAAiNBVhqQBRhsCOgpIJQisQEahQCVAAIALAAQC/AACECHQCHCEAAC/MAAAA01QAAC7iHCHQiECEi/AAQi7AAiHiEg");
	this.shape.setTransform(110,270.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(19.9,56,180.2,429.5);


(libIntro.IntroMovie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.intro_NXT_btn = new libIntro.intro_invisible();
	this.intro_NXT_btn.setTransform(876.9,511.9,1,1,0,0,0,48,65);
	new cjs.ButtonHelper(this.intro_NXT_btn, 0, 1, 2, false, new libIntro.intro_invisible(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.intro_NXT_btn}]}).wait(155));

	// Layer 3
	this.instance = new libIntro.arrow_bottom();
	this.instance.setTransform(881.4,547.1,1,1,0,0,180,19.9,48.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(115).to({_off:false},0).wait(40));

	// white arrow mask
	this.instance_1 = new libIntro.whiterec2("synched",0);
	this.instance_1.setTransform(644.4,554.7,1.209,1.121,0,0,0,211.1,33);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(105).to({startPosition:0,_off:false},0).to({x:1124.4},10).to({_off:true},1).wait(39));

	// Red Arrow Line
	this.instance_2 = new libIntro.RedArrowLine("synched",0);
	this.instance_2.setTransform(626.4,547.9,1,1,0,0,0,236.3,22.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(105).to({startPosition:0,_off:false},0).wait(50));

	// Fast fact
	this.instance_3 = new libIntro.FastFact("synched",0);
	this.instance_3.setTransform(18.3,407.7,1,1,0,0,0,709.4,140);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(90).to({startPosition:0,_off:false},0).to({alpha:1},15).to({startPosition:0},49).wait(1));

	// A Look Back
	this.instance_4 = new libIntro.YearInReview("synched",0);
	this.instance_4.setTransform(4.4,-1.7,1,1,0,0,0,609.1,72.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(70).to({startPosition:0,_off:false},0).to({scaleX:1.2,scaleY:1.2,alpha:1},6).to({scaleX:1,scaleY:1},3).to({startPosition:0},75).wait(1));

	// 3
	this.instance_5 = new libIntro._3("synched",0);
	this.instance_5.setTransform(650.1,-963.7,1,1,0,0,0,260,302);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(63).to({startPosition:0,_off:false},0).to({y:20.2},10,cjs.Ease.get(1)).to({startPosition:0},6).to({startPosition:0},75).wait(1));

	// 1
	this.instance_6 = new libIntro._1("synched",0);
	this.instance_6.setTransform(446.2,1022.2,1,1,0,0,0,260,302);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(63).to({startPosition:0,_off:false},0).to({y:24.2},10,cjs.Ease.get(1)).to({startPosition:0},6).to({startPosition:0},75).wait(1));

	// 2
	this.instance_7 = new libIntro._2("synched",0);
	this.instance_7.setTransform(-303.8,-955.7,1,1,0,0,0,260,302);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(63).to({startPosition:0,_off:false},0).to({y:26.2},10,cjs.Ease.get(1)).to({startPosition:0},6).to({startPosition:0},75).wait(1));

	// Logo
	this.instance_8 = new libIntro.Logo("synched",0);
	this.instance_8.setTransform(-611.5,987.3,0.215,0.215,-89.9,0,0,984.1,148.5);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(63).to({startPosition:0,_off:false},0).to({y:-6.5},10,cjs.Ease.get(1)).to({startPosition:0},6).to({startPosition:0},75).wait(1));

	// Red Ball
	this.instance_9 = new libIntro.RedCircle("synched",0);
	this.instance_9.setTransform(2.1,-0.5,0.137,0.137,0,0,0,233,233);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(59).to({startPosition:0,_off:false},0).to({scaleX:0.94,scaleY:0.94,x:2.2},4).to({startPosition:0},6).to({startPosition:0},10).to({startPosition:0},75).wait(1));

	// white rec2 mask top
	this.instance_10 = new libIntro.whiterec2("synched",0);
	this.instance_10.setTransform(-0.6,-44.7,1,1,0,0,0,211.1,33);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(20).to({startPosition:0,_off:false},0).to({x:421.3},9).to({x:-0.6,y:-90.6},1).to({x:-440.6},4).to({x:-72.5,y:-178.6},1).to({x:-334.5},4).to({x:89.3,y:-210.6},1).to({x:305.3},3).to({x:-158.6,y:-230.6},1).to({x:-240.6},2).to({x:-1236.8,y:-38.6},1).to({scaleX:4.86,x:-1236.6},12).to({startPosition:0},4).to({_off:true},1).wait(91));

	// white rec2 mask bottom
	this.instance_11 = new libIntro.whiterec2("synched",0);
	this.instance_11.setTransform(-0.6,31.2,1,1,0,0,0,211.1,33);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(20).to({startPosition:0,_off:false},0).to({x:-422.5},9).to({x:1.2,y:93.2},1).to({x:411.2},4).to({x:73.1,y:179.2},1).to({x:339.1},4).to({x:-86.8,y:211.2},1).to({x:-302.8},3).to({x:151.1,y:231.2},1).to({x:1237.4,y:37.2},2).to({startPosition:0},1).to({scaleX:4.87,x:1237.6},12).to({startPosition:0},4).to({_off:true},1).wait(91));

	// mask
	this.instance_12 = new libIntro.whitebox("synched",0);
	this.instance_12.setTransform(2.3,-327.8,0.198,1,0,0,0,1031.3,270.1);

	this.instance_13 = new libIntro.whitebox("synched",0);
	this.instance_13.setTransform(6.3,330.3,0.198,1,0,0,0,1031.3,270.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13,p:{y:330.3}},{t:this.instance_12,p:{y:-327.8}}]},20).to({state:[{t:this.instance_13,p:{y:378.3}},{t:this.instance_12,p:{y:-377.8}}]},10).to({state:[{t:this.instance_13,p:{y:448.3}},{t:this.instance_12,p:{y:-445.8}}]},5).to({state:[{t:this.instance_13,p:{y:468.3}},{t:this.instance_12,p:{y:-467.8}}]},5).to({state:[]},4).wait(111));

	// White
	this.instance_14 = new libIntro.whitebox("synched",0);
	this.instance_14.setTransform(-0.7,-23.7,1,1,0,0,0,1031.2,270.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({scaleX:0.21,x:-0.5},19).to({_off:true},1).wait(135));

	// Wrap Ball
	this.instance_15 = new libIntro.WrapBall("synched",0);
	this.instance_15.setTransform(101.3,1.2,1,1,0,0,0,1729.4,205.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},64).wait(91));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1628.1,-293.8,3458.8,870.7);

})(libIntro = libIntro||{}, images = images||{}, createjs = createjs||{});
var libIntro, images, createjs;